#!/usr/bin/env python3
"""
Regenerate correlation heatmaps from pre-generated CSV files.

This script reads correlation CSV files generated by analyze_latent_correlations.py
and creates visualization heatmaps. Useful for regenerating plots without re-running
the full analysis.

Usage:
    python scripts/plot_correlation_heatmaps.py <csv_directory> [--output OUTPUT_DIR]

Example:
    python scripts/plot_correlation_heatmaps.py correlation_analysis_exp_244072d3529b
    python scripts/plot_correlation_heatmaps.py correlation_analysis_exp_244072d3529b --output ./plots
"""

import argparse
import sys
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend
import matplotlib.pyplot as plt


def load_correlation_csvs(csv_dir: Path) -> dict:
    """Load correlation matrices from CSV files.
    
    Args:
        csv_dir: Directory containing CSV files
        
    Returns:
        Dictionary with correlation matrices and metadata
    """
    csv_dir = Path(csv_dir)
    
    if not csv_dir.exists():
        raise FileNotFoundError(f"Directory not found: {csv_dir}")
    
    correlations = {}
    
    # Load each correlation type
    for corr_type in ['pearson', 'spearman', 'mutual_info']:
        csv_path = csv_dir / f'{corr_type}_correlations.csv'
        if csv_path.exists():
            df = pd.read_csv(csv_path, index_col=0)
            correlations[corr_type] = df.values
            correlations[f'{corr_type}_df'] = df
    
    if not correlations:
        raise ValueError(f"No correlation CSV files found in {csv_dir}")
    
    # Extract latent and parameter names from first DataFrame
    first_df = correlations['pearson_df'] if 'pearson_df' in correlations else correlations['spearman_df']
    correlations['latent_dim_names'] = first_df.index.tolist()
    correlations['param_names'] = first_df.columns.tolist()
    
    return correlations


def create_heatmaps_from_csvs(correlations: dict, output_dir: Path):
    """Create correlation heatmaps from loaded CSV data.
    
    Args:
        correlations: Dictionary with correlation matrices
        output_dir: Directory to save plots
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    latent_dim_names = correlations['latent_dim_names']
    param_names = correlations['param_names']
    
    # Create heatmaps for each correlation type
    for corr_type in ['pearson', 'spearman', 'mutual_info']:
        if corr_type not in correlations:
            print(f"Warning: {corr_type} correlations not found, skipping...")
            continue
        
        corr_matrix = correlations[corr_type]
        
        # Create figure with appropriate size
        fig_width = max(12, len(param_names) * 0.5)
        fig_height = max(8, len(latent_dim_names) * 0.3)
        fig, ax = plt.subplots(figsize=(fig_width, fig_height))
        
        # Determine colormap and value range
        if corr_type == 'mutual_info':
            vmin = 0
            vmax = None  # Auto-scale
            cmap = 'viridis'
        else:
            vmin = -1
            vmax = 1
            cmap = 'RdBu_r'
        
        # Create heatmap
        im = ax.imshow(
            corr_matrix,
            aspect='auto',
            cmap=cmap,
            vmin=vmin,
            vmax=vmax,
            interpolation='nearest',
            origin='upper'
        )
        
        # Set ticks and labels
        ax.set_xticks(range(len(param_names)))
        ax.set_xticklabels(param_names, rotation=45, ha='right', fontsize=8)
        ax.set_yticks(range(len(latent_dim_names)))
        ax.set_yticklabels(latent_dim_names, fontsize=8)
        
        # Add colorbar
        cbar = plt.colorbar(im, ax=ax)
        cbar.set_label(corr_type.replace('_', ' ').title(), fontsize=10)
        
        # Set title and labels
        title = f'{corr_type.replace("_", " ").title()} Correlation: Latent Dimensions vs Parameters'
        ax.set_title(title, fontsize=12, pad=20)
        ax.set_xlabel('Parameters', fontsize=10)
        ax.set_ylabel('Latent Dimensions', fontsize=10)
        
        # Adjust layout
        plt.tight_layout()
        
        # Save figure
        output_path = output_dir / f'{corr_type}_correlation_heatmap.png'
        plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
        print(f"Saved {corr_type} heatmap to {output_path}")
        plt.close(fig)
    
    # Create summary heatmap showing maximum absolute correlation
    if 'pearson' in correlations and 'spearman' in correlations:
        max_abs_corr = np.maximum(
            np.abs(correlations['pearson']),
            np.abs(correlations['spearman'])
        )
        
        fig, ax = plt.subplots(figsize=(max(12, len(param_names) * 0.5), max(8, len(latent_dim_names) * 0.3)))
        
        im = ax.imshow(
            max_abs_corr,
            aspect='auto',
            cmap='YlOrRd',
            vmin=0,
            vmax=1,
            interpolation='nearest',
            origin='upper'
        )
        
        # Set ticks and labels
        ax.set_xticks(range(len(param_names)))
        ax.set_xticklabels(param_names, rotation=45, ha='right', fontsize=8)
        ax.set_yticks(range(len(latent_dim_names)))
        ax.set_yticklabels(latent_dim_names, fontsize=8)
        
        # Add colorbar
        cbar = plt.colorbar(im, ax=ax)
        cbar.set_label('Max Absolute Correlation', fontsize=10)
        
        ax.set_title('Maximum Absolute Correlation: Latent Dimensions vs Parameters', fontsize=12, pad=20)
        ax.set_xlabel('Parameters', fontsize=10)
        ax.set_ylabel('Latent Dimensions', fontsize=10)
        plt.tight_layout()
        
        output_path = output_dir / 'max_absolute_correlation_heatmap.png'
        plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
        print(f"Saved max absolute correlation heatmap to {output_path}")
        plt.close(fig)


def print_summary_statistics(correlations: dict):
    """Print summary statistics from correlations.
    
    Args:
        correlations: Dictionary with correlation matrices
    """
    print("\n=== Summary Statistics ===")
    print(f"Latent dimensions: {len(correlations['latent_dim_names'])}")
    print(f"Parameters: {len(correlations['param_names'])}")
    
    if 'pearson' in correlations:
        pearson = correlations['pearson']
        pearson_abs = np.abs(pearson)
        max_corr_idx = np.unravel_index(np.argmax(pearson_abs), pearson_abs.shape)
        print(f"\nStrongest Pearson correlation: {pearson[max_corr_idx]:.3f}")
        print(f"  Latent: {correlations['latent_dim_names'][max_corr_idx[0]]}")
        print(f"  Parameter: {correlations['param_names'][max_corr_idx[1]]}")
        
        # Count strong correlations
        strong_corr = (np.abs(pearson) > 0.5).sum()
        print(f"\nStrong correlations (|r| > 0.5): {strong_corr}")


def main():
    parser = argparse.ArgumentParser(description='Regenerate correlation heatmaps from CSV files')
    parser.add_argument('csv_directory', help='Directory containing correlation CSV files')
    parser.add_argument('--output', type=Path, default=None,
                       help='Output directory for plots (default: same as input directory)')
    
    args = parser.parse_args()
    
    csv_dir = Path(args.csv_directory)
    
    if args.output is None:
        output_dir = csv_dir
    else:
        output_dir = Path(args.output)
    
    print(f"Loading correlation CSVs from: {csv_dir}")
    
    # Load correlations
    try:
        correlations = load_correlation_csvs(csv_dir)
    except Exception as e:
        print(f"Error loading CSV files: {e}")
        sys.exit(1)
    
    print(f"Loaded correlations for {len(correlations['latent_dim_names'])} latent dimensions")
    print(f"and {len(correlations['param_names'])} parameters")
    
    # Create heatmaps
    print(f"\nGenerating heatmaps...")
    create_heatmaps_from_csvs(correlations, output_dir)
    
    # Print summary
    print_summary_statistics(correlations)
    
    print(f"\nHeatmaps saved to: {output_dir}")


if __name__ == '__main__':
    main()







